"""Translations beyond the two the application started with.

Vietnamese lives in `i18n.py` because it is complete; these seven cover the
interface people actually look at - the toolbar, the menus, the table, the
states, the add and settings dialogs - and let everything else fall back to
English. A half-translated screen with an English word in it is honest; a
mistranslated one is not, so nothing is guessed at here.

The keys are the English strings, exactly as they appear in the code.
"""

from __future__ import annotations

#: code -> what to call the language *in* that language
NAMES = {
    "zh": "简体中文",
    "ja": "日本語",
    "ko": "한국어",
    "es": "Español",
    "fr": "Français",
    "de": "Deutsch",
    "ru": "Русский",
}

ZH = {
    "Add URL": "添加链接", "Resume": "继续", "Pause": "暂停",
    "Pause All": "全部暂停", "Resume All": "全部继续", "Delete": "删除",
    "Options": "选项", "Scheduler": "计划任务", "File": "文件",
    "Downloads": "下载", "Help": "帮助", "Exit": "退出", "About": "关于",
    "Open": "打开文件", "Open Folder": "打开所在文件夹", "Copy URL": "复制链接",
    "Properties": "属性", "Redownload": "重新下载",
    "Remove from list": "从列表移除", "Delete file too": "同时删除文件",
    "Name": "文件名", "Size": "大小", "Status": "状态", "Progress": "进度",
    "Left": "剩余", "Speed": "速度", "Added": "添加时间", "Search": "搜索",
    "All downloads": "全部", "Unfinished": "未完成", "Finished": "已完成",
    "General": "其他", "Video": "视频", "Music": "音乐", "Compressed": "压缩包",
    "Documents": "文档", "Programs": "程序",
    "queued": "排队中", "probing": "检测中", "downloading": "下载中",
    "paused": "已暂停", "completed": "已完成", "error": "错误", "cancelled": "已取消",
    "Add a download": "添加下载", "Address:": "地址:", "Save to:": "保存到:",
    "File name:": "文件名:", "Category:": "分类:", "Connections:": "连接数:",
    "Browse...": "浏览...", "Advanced": "高级", "Speed limit:": "限速:",
    "Download now": "立即下载", "Download later": "稍后下载", "Cancel": "取消",
    "auto": "自动", "unlimited": "不限",
    "Download progress": "下载进度", "Transfer rate": "传输速度",
    "Segments": "分段", "Time left:": "剩余时间:", "Transferred:": "已下载:",
    "Close": "关闭", "Open file when done": "完成后打开文件",
    "Settings": "设置", "Downloads folder:": "下载文件夹:",
    "Default connections:": "默认连接数:", "Simultaneous downloads:": "同时下载数:",
    "Global speed limit:": "全局限速:", "Language:": "语言:", "Theme:": "主题",
    "General settings": "常规", "Connection": "连接", "Save": "保存",
    "Nothing selected.": "未选择任何项目。", "Enter a URL": "请输入链接",
    "Delete the selected downloads?": "删除选中的下载?",
    "The file no longer exists.": "文件已不存在。",
    "Downloading": "正在下载", "idle": "空闲", "Total speed": "总速度",
    "Show window": "显示窗口", "Browser integration": "浏览器集成",
    "Register": "注册", "Remove": "移除", "Not registered yet": "尚未注册",
    "Queues": "队列", "Queue:": "队列:", "No queue": "不排队",
    "Sound effects": "音效", "Volume:": "音量:", "Listen": "试听",
    "Download town": "下载小镇", "All downloads finished": "全部下载完成",
    "Nothing downloading - the town is quiet": "没有下载 — 小镇很安静",
    "History": "历史记录", "Statistics": "统计", "Site rules": "站点规则",
    "Add many URLs": "批量添加", "Site Grabber": "网站抓取",
    "Follow Windows": "跟随系统", "Verify checksum": "校验文件",
}

JA = {
    "Add URL": "URLを追加", "Resume": "再開", "Pause": "一時停止",
    "Pause All": "すべて一時停止", "Resume All": "すべて再開", "Delete": "削除",
    "Options": "オプション", "Scheduler": "スケジュール", "File": "ファイル",
    "Downloads": "ダウンロード", "Help": "ヘルプ", "Exit": "終了", "About": "情報",
    "Open": "ファイルを開く", "Open Folder": "フォルダーを開く",
    "Copy URL": "URLをコピー", "Properties": "プロパティ",
    "Redownload": "再ダウンロード", "Remove from list": "一覧から削除",
    "Delete file too": "ファイルも削除",
    "Name": "ファイル名", "Size": "サイズ", "Status": "状態", "Progress": "進行状況",
    "Left": "残り", "Speed": "速度", "Added": "追加日時", "Search": "検索",
    "All downloads": "すべて", "Unfinished": "未完了", "Finished": "完了",
    "General": "その他", "Video": "動画", "Music": "音楽", "Compressed": "圧縮",
    "Documents": "文書", "Programs": "プログラム",
    "queued": "待機中", "probing": "確認中", "downloading": "ダウンロード中",
    "paused": "一時停止", "completed": "完了", "error": "エラー", "cancelled": "キャンセル",
    "Add a download": "ダウンロードを追加", "Address:": "アドレス:",
    "Save to:": "保存先:", "File name:": "ファイル名:", "Category:": "カテゴリ:",
    "Connections:": "接続数:", "Browse...": "参照...", "Advanced": "詳細設定",
    "Speed limit:": "速度制限:", "Download now": "今すぐダウンロード",
    "Download later": "後でダウンロード", "Cancel": "キャンセル",
    "auto": "自動", "unlimited": "無制限",
    "Download progress": "ダウンロードの進行状況", "Transfer rate": "転送速度",
    "Segments": "セグメント", "Time left:": "残り時間:", "Transferred:": "転送済み:",
    "Close": "閉じる", "Open file when done": "完了時にファイルを開く",
    "Settings": "設定", "Downloads folder:": "保存フォルダー:",
    "Default connections:": "既定の接続数:", "Simultaneous downloads:": "同時ダウンロード数:",
    "Global speed limit:": "全体の速度制限:", "Language:": "言語:", "Theme:": "テーマ",
    "General settings": "全般", "Connection": "接続", "Save": "保存",
    "Nothing selected.": "選択されていません。", "Enter a URL": "URLを入力してください",
    "Delete the selected downloads?": "選択したダウンロードを削除しますか?",
    "The file no longer exists.": "ファイルが見つかりません。",
    "Downloading": "ダウンロード中", "idle": "待機", "Total speed": "合計速度",
    "Show window": "ウィンドウを表示", "Browser integration": "ブラウザー連携",
    "Register": "登録", "Remove": "解除", "Not registered yet": "未登録",
    "Queues": "キュー", "Queue:": "キュー:", "No queue": "キューなし",
    "Sound effects": "効果音", "Volume:": "音量:", "Listen": "試聴",
    "Download town": "ダウンロードの街", "All downloads finished": "すべて完了しました",
    "Nothing downloading - the town is quiet": "ダウンロードなし — 街は静かです",
    "History": "履歴", "Statistics": "統計", "Site rules": "サイト別の設定",
    "Add many URLs": "URLをまとめて追加", "Site Grabber": "サイト取り込み",
    "Follow Windows": "Windowsに合わせる", "Verify checksum": "チェックサム確認",
}

KO = {
    "Add URL": "URL 추가", "Resume": "계속", "Pause": "일시정지",
    "Pause All": "모두 일시정지", "Resume All": "모두 계속", "Delete": "삭제",
    "Options": "옵션", "Scheduler": "예약", "File": "파일",
    "Downloads": "다운로드", "Help": "도움말", "Exit": "종료", "About": "정보",
    "Open": "파일 열기", "Open Folder": "폴더 열기", "Copy URL": "URL 복사",
    "Properties": "속성", "Redownload": "다시 다운로드",
    "Remove from list": "목록에서 제거", "Delete file too": "파일도 삭제",
    "Name": "파일 이름", "Size": "크기", "Status": "상태", "Progress": "진행률",
    "Left": "남음", "Speed": "속도", "Added": "추가한 날짜", "Search": "검색",
    "All downloads": "전체", "Unfinished": "미완료", "Finished": "완료",
    "General": "기타", "Video": "동영상", "Music": "음악", "Compressed": "압축",
    "Documents": "문서", "Programs": "프로그램",
    "queued": "대기 중", "probing": "확인 중", "downloading": "다운로드 중",
    "paused": "일시정지", "completed": "완료", "error": "오류", "cancelled": "취소됨",
    "Add a download": "다운로드 추가", "Address:": "주소:", "Save to:": "저장 위치:",
    "File name:": "파일 이름:", "Category:": "분류:", "Connections:": "연결 수:",
    "Browse...": "찾아보기...", "Advanced": "고급", "Speed limit:": "속도 제한:",
    "Download now": "지금 다운로드", "Download later": "나중에 다운로드",
    "Cancel": "취소", "auto": "자동", "unlimited": "무제한",
    "Download progress": "다운로드 진행", "Transfer rate": "전송 속도",
    "Segments": "구간", "Time left:": "남은 시간:", "Transferred:": "전송됨:",
    "Close": "닫기", "Open file when done": "완료되면 파일 열기",
    "Settings": "설정", "Downloads folder:": "다운로드 폴더:",
    "Default connections:": "기본 연결 수:", "Simultaneous downloads:": "동시 다운로드 수:",
    "Global speed limit:": "전체 속도 제한:", "Language:": "언어:", "Theme:": "테마",
    "General settings": "일반", "Connection": "연결", "Save": "저장",
    "Nothing selected.": "선택된 항목이 없습니다.", "Enter a URL": "URL을 입력하세요",
    "Delete the selected downloads?": "선택한 다운로드를 삭제할까요?",
    "The file no longer exists.": "파일이 더 이상 없습니다.",
    "Downloading": "다운로드 중", "idle": "대기", "Total speed": "전체 속도",
    "Show window": "창 표시", "Browser integration": "브라우저 연동",
    "Register": "등록", "Remove": "해제", "Not registered yet": "등록되지 않음",
    "Queues": "대기열", "Queue:": "대기열:", "No queue": "대기열 없음",
    "Sound effects": "효과음", "Volume:": "음량:", "Listen": "미리 듣기",
    "Download town": "다운로드 마을", "All downloads finished": "모두 완료되었습니다",
    "Nothing downloading - the town is quiet": "다운로드 없음 — 마을이 조용합니다",
    "History": "기록", "Statistics": "통계", "Site rules": "사이트 규칙",
    "Add many URLs": "여러 URL 추가", "Site Grabber": "사이트 수집",
    "Follow Windows": "Windows 설정 따르기", "Verify checksum": "체크섬 확인",
}

ES = {
    "Add URL": "Añadir URL", "Resume": "Reanudar", "Pause": "Pausar",
    "Pause All": "Pausar todo", "Resume All": "Reanudar todo", "Delete": "Eliminar",
    "Options": "Opciones", "Scheduler": "Programador", "File": "Archivo",
    "Downloads": "Descargas", "Help": "Ayuda", "Exit": "Salir", "About": "Acerca de",
    "Open": "Abrir archivo", "Open Folder": "Abrir carpeta", "Copy URL": "Copiar URL",
    "Properties": "Propiedades", "Redownload": "Volver a descargar",
    "Remove from list": "Quitar de la lista", "Delete file too": "Eliminar también el archivo",
    "Name": "Nombre", "Size": "Tamaño", "Status": "Estado", "Progress": "Progreso",
    "Left": "Restante", "Speed": "Velocidad", "Added": "Añadido", "Search": "Buscar",
    "All downloads": "Todas", "Unfinished": "Sin terminar", "Finished": "Terminadas",
    "General": "Otros", "Video": "Vídeo", "Music": "Música", "Compressed": "Comprimidos",
    "Documents": "Documentos", "Programs": "Programas",
    "queued": "en cola", "probing": "comprobando", "downloading": "descargando",
    "paused": "en pausa", "completed": "completada", "error": "error", "cancelled": "cancelada",
    "Add a download": "Añadir una descarga", "Address:": "Dirección:",
    "Save to:": "Guardar en:", "File name:": "Nombre del archivo:",
    "Category:": "Categoría:", "Connections:": "Conexiones:", "Browse...": "Examinar...",
    "Advanced": "Avanzado", "Speed limit:": "Límite de velocidad:",
    "Download now": "Descargar ahora", "Download later": "Descargar después",
    "Cancel": "Cancelar", "auto": "automático", "unlimited": "sin límite",
    "Download progress": "Progreso de la descarga", "Transfer rate": "Velocidad de transferencia",
    "Segments": "Segmentos", "Time left:": "Tiempo restante:", "Transferred:": "Transferido:",
    "Close": "Cerrar", "Open file when done": "Abrir el archivo al terminar",
    "Settings": "Configuración", "Downloads folder:": "Carpeta de descargas:",
    "Default connections:": "Conexiones por defecto:",
    "Simultaneous downloads:": "Descargas simultáneas:",
    "Global speed limit:": "Límite de velocidad global:", "Language:": "Idioma:",
    "Theme:": "Tema", "General settings": "General", "Connection": "Conexión",
    "Save": "Guardar", "Nothing selected.": "No hay nada seleccionado.",
    "Enter a URL": "Introduce una URL",
    "Delete the selected downloads?": "¿Eliminar las descargas seleccionadas?",
    "The file no longer exists.": "El archivo ya no existe.",
    "Downloading": "Descargando", "idle": "inactivo", "Total speed": "Velocidad total",
    "Show window": "Mostrar ventana", "Browser integration": "Integración con el navegador",
    "Register": "Registrar", "Remove": "Quitar", "Not registered yet": "Sin registrar",
    "Queues": "Colas", "Queue:": "Cola:", "No queue": "Sin cola",
    "Sound effects": "Efectos de sonido", "Volume:": "Volumen:", "Listen": "Escuchar",
    "Download town": "Ciudad de descargas", "All downloads finished": "Todas las descargas han terminado",
    "Nothing downloading - the town is quiet": "Nada en descarga: la ciudad está tranquila",
    "History": "Historial", "Statistics": "Estadísticas", "Site rules": "Reglas por sitio",
    "Add many URLs": "Añadir varias URL", "Site Grabber": "Rastreador de sitios",
    "Follow Windows": "Seguir a Windows", "Verify checksum": "Verificar suma",
}

FR = {
    "Add URL": "Ajouter une URL", "Resume": "Reprendre", "Pause": "Suspendre",
    "Pause All": "Tout suspendre", "Resume All": "Tout reprendre", "Delete": "Supprimer",
    "Options": "Options", "Scheduler": "Planificateur", "File": "Fichier",
    "Downloads": "Téléchargements", "Help": "Aide", "Exit": "Quitter", "About": "À propos",
    "Open": "Ouvrir le fichier", "Open Folder": "Ouvrir le dossier",
    "Copy URL": "Copier l'URL", "Properties": "Propriétés",
    "Redownload": "Retélécharger", "Remove from list": "Retirer de la liste",
    "Delete file too": "Supprimer aussi le fichier",
    "Name": "Nom", "Size": "Taille", "Status": "État", "Progress": "Progression",
    "Left": "Restant", "Speed": "Vitesse", "Added": "Ajouté", "Search": "Rechercher",
    "All downloads": "Tout", "Unfinished": "Inachevés", "Finished": "Terminés",
    "General": "Autres", "Video": "Vidéo", "Music": "Musique", "Compressed": "Archives",
    "Documents": "Documents", "Programs": "Programmes",
    "queued": "en attente", "probing": "vérification", "downloading": "téléchargement",
    "paused": "suspendu", "completed": "terminé", "error": "erreur", "cancelled": "annulé",
    "Add a download": "Ajouter un téléchargement", "Address:": "Adresse :",
    "Save to:": "Enregistrer dans :", "File name:": "Nom du fichier :",
    "Category:": "Catégorie :", "Connections:": "Connexions :", "Browse...": "Parcourir...",
    "Advanced": "Avancé", "Speed limit:": "Limite de vitesse :",
    "Download now": "Télécharger maintenant", "Download later": "Télécharger plus tard",
    "Cancel": "Annuler", "auto": "auto", "unlimited": "illimité",
    "Download progress": "Progression du téléchargement", "Transfer rate": "Débit",
    "Segments": "Segments", "Time left:": "Temps restant :", "Transferred:": "Transféré :",
    "Close": "Fermer", "Open file when done": "Ouvrir le fichier une fois terminé",
    "Settings": "Paramètres", "Downloads folder:": "Dossier de téléchargement :",
    "Default connections:": "Connexions par défaut :",
    "Simultaneous downloads:": "Téléchargements simultanés :",
    "Global speed limit:": "Limite de vitesse globale :", "Language:": "Langue :",
    "Theme:": "Thème", "General settings": "Général", "Connection": "Connexion",
    "Save": "Enregistrer", "Nothing selected.": "Aucune sélection.",
    "Enter a URL": "Saisissez une URL",
    "Delete the selected downloads?": "Supprimer les téléchargements sélectionnés ?",
    "The file no longer exists.": "Le fichier n'existe plus.",
    "Downloading": "Téléchargement", "idle": "inactif", "Total speed": "Vitesse totale",
    "Show window": "Afficher la fenêtre", "Browser integration": "Intégration au navigateur",
    "Register": "Enregistrer", "Remove": "Retirer", "Not registered yet": "Non enregistré",
    "Queues": "Files d'attente", "Queue:": "File :", "No queue": "Aucune file",
    "Sound effects": "Effets sonores", "Volume:": "Volume :", "Listen": "Écouter",
    "Download town": "La ville des téléchargements",
    "All downloads finished": "Tous les téléchargements sont terminés",
    "Nothing downloading - the town is quiet": "Rien en cours — la ville est calme",
    "History": "Historique", "Statistics": "Statistiques", "Site rules": "Règles par site",
    "Add many URLs": "Ajouter plusieurs URL", "Site Grabber": "Aspirateur de site",
    "Follow Windows": "Suivre Windows", "Verify checksum": "Vérifier l'empreinte",
}

DE = {
    "Add URL": "URL hinzufügen", "Resume": "Fortsetzen", "Pause": "Anhalten",
    "Pause All": "Alle anhalten", "Resume All": "Alle fortsetzen", "Delete": "Löschen",
    "Options": "Optionen", "Scheduler": "Zeitplan", "File": "Datei",
    "Downloads": "Downloads", "Help": "Hilfe", "Exit": "Beenden", "About": "Über",
    "Open": "Datei öffnen", "Open Folder": "Ordner öffnen", "Copy URL": "URL kopieren",
    "Properties": "Eigenschaften", "Redownload": "Erneut herunterladen",
    "Remove from list": "Aus der Liste entfernen", "Delete file too": "Datei ebenfalls löschen",
    "Name": "Name", "Size": "Größe", "Status": "Status", "Progress": "Fortschritt",
    "Left": "Verbleibend", "Speed": "Geschwindigkeit", "Added": "Hinzugefügt",
    "Search": "Suchen", "All downloads": "Alle", "Unfinished": "Unfertig",
    "Finished": "Fertig", "General": "Sonstiges", "Video": "Video", "Music": "Musik",
    "Compressed": "Archive", "Documents": "Dokumente", "Programs": "Programme",
    "queued": "in der Warteschlange", "probing": "wird geprüft", "downloading": "lädt",
    "paused": "angehalten", "completed": "fertig", "error": "Fehler", "cancelled": "abgebrochen",
    "Add a download": "Download hinzufügen", "Address:": "Adresse:",
    "Save to:": "Speichern unter:", "File name:": "Dateiname:", "Category:": "Kategorie:",
    "Connections:": "Verbindungen:", "Browse...": "Durchsuchen...", "Advanced": "Erweitert",
    "Speed limit:": "Geschwindigkeitslimit:", "Download now": "Jetzt herunterladen",
    "Download later": "Später herunterladen", "Cancel": "Abbrechen",
    "auto": "automatisch", "unlimited": "unbegrenzt",
    "Download progress": "Download-Fortschritt", "Transfer rate": "Übertragungsrate",
    "Segments": "Segmente", "Time left:": "Restzeit:", "Transferred:": "Übertragen:",
    "Close": "Schließen", "Open file when done": "Datei nach Abschluss öffnen",
    "Settings": "Einstellungen", "Downloads folder:": "Download-Ordner:",
    "Default connections:": "Standardverbindungen:",
    "Simultaneous downloads:": "Gleichzeitige Downloads:",
    "Global speed limit:": "Globales Geschwindigkeitslimit:", "Language:": "Sprache:",
    "Theme:": "Design", "General settings": "Allgemein", "Connection": "Verbindung",
    "Save": "Speichern", "Nothing selected.": "Nichts ausgewählt.",
    "Enter a URL": "Bitte eine URL eingeben",
    "Delete the selected downloads?": "Ausgewählte Downloads löschen?",
    "The file no longer exists.": "Die Datei existiert nicht mehr.",
    "Downloading": "Lädt", "idle": "untätig", "Total speed": "Gesamtgeschwindigkeit",
    "Show window": "Fenster anzeigen", "Browser integration": "Browser-Integration",
    "Register": "Registrieren", "Remove": "Entfernen", "Not registered yet": "Noch nicht registriert",
    "Queues": "Warteschlangen", "Queue:": "Warteschlange:", "No queue": "Keine Warteschlange",
    "Sound effects": "Soundeffekte", "Volume:": "Lautstärke:", "Listen": "Anhören",
    "Download town": "Download-Stadt", "All downloads finished": "Alle Downloads sind fertig",
    "Nothing downloading - the town is quiet": "Nichts lädt — die Stadt ist still",
    "History": "Verlauf", "Statistics": "Statistik", "Site rules": "Seitenregeln",
    "Add many URLs": "Mehrere URLs hinzufügen", "Site Grabber": "Website-Grabber",
    "Follow Windows": "Windows folgen", "Verify checksum": "Prüfsumme prüfen",
}

RU = {
    "Add URL": "Добавить ссылку", "Resume": "Продолжить", "Pause": "Пауза",
    "Pause All": "Остановить всё", "Resume All": "Продолжить всё", "Delete": "Удалить",
    "Options": "Настройки", "Scheduler": "Планировщик", "File": "Файл",
    "Downloads": "Загрузки", "Help": "Справка", "Exit": "Выход", "About": "О программе",
    "Open": "Открыть файл", "Open Folder": "Открыть папку", "Copy URL": "Копировать ссылку",
    "Properties": "Свойства", "Redownload": "Скачать заново",
    "Remove from list": "Убрать из списка", "Delete file too": "Удалить и файл",
    "Name": "Имя файла", "Size": "Размер", "Status": "Состояние", "Progress": "Прогресс",
    "Left": "Осталось", "Speed": "Скорость", "Added": "Добавлено", "Search": "Поиск",
    "All downloads": "Все", "Unfinished": "Незавершённые", "Finished": "Завершённые",
    "General": "Прочее", "Video": "Видео", "Music": "Музыка", "Compressed": "Архивы",
    "Documents": "Документы", "Programs": "Программы",
    "queued": "в очереди", "probing": "проверка", "downloading": "загрузка",
    "paused": "приостановлено", "completed": "завершено", "error": "ошибка",
    "cancelled": "отменено",
    "Add a download": "Добавить загрузку", "Address:": "Адрес:",
    "Save to:": "Сохранить в:", "File name:": "Имя файла:", "Category:": "Категория:",
    "Connections:": "Соединений:", "Browse...": "Обзор...", "Advanced": "Дополнительно",
    "Speed limit:": "Ограничение скорости:", "Download now": "Скачать сейчас",
    "Download later": "Скачать позже", "Cancel": "Отмена",
    "auto": "авто", "unlimited": "без ограничений",
    "Download progress": "Ход загрузки", "Transfer rate": "Скорость передачи",
    "Segments": "Сегменты", "Time left:": "Осталось времени:", "Transferred:": "Передано:",
    "Close": "Закрыть", "Open file when done": "Открыть файл по завершении",
    "Settings": "Параметры", "Downloads folder:": "Папка загрузок:",
    "Default connections:": "Соединений по умолчанию:",
    "Simultaneous downloads:": "Одновременных загрузок:",
    "Global speed limit:": "Общее ограничение скорости:", "Language:": "Язык:",
    "Theme:": "Тема", "General settings": "Общие", "Connection": "Соединение",
    "Save": "Сохранить", "Nothing selected.": "Ничего не выбрано.",
    "Enter a URL": "Введите ссылку",
    "Delete the selected downloads?": "Удалить выбранные загрузки?",
    "The file no longer exists.": "Файла больше нет.",
    "Downloading": "Загрузка", "idle": "простой", "Total speed": "Общая скорость",
    "Show window": "Показать окно", "Browser integration": "Интеграция с браузером",
    "Register": "Зарегистрировать", "Remove": "Убрать", "Not registered yet": "Не зарегистрировано",
    "Queues": "Очереди", "Queue:": "Очередь:", "No queue": "Без очереди",
    "Sound effects": "Звуковые эффекты", "Volume:": "Громкость:", "Listen": "Прослушать",
    "Download town": "Город загрузок", "All downloads finished": "Все загрузки завершены",
    "Nothing downloading - the town is quiet": "Загрузок нет — в городе тихо",
    "History": "История", "Statistics": "Статистика", "Site rules": "Правила сайтов",
    "Add many URLs": "Добавить много ссылок", "Site Grabber": "Сбор с сайта",
    "Follow Windows": "Как в Windows", "Verify checksum": "Проверить контрольную сумму",
}

TABLES = {"zh": ZH, "ja": JA, "ko": KO, "es": ES, "fr": FR, "de": DE, "ru": RU}
